version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building Spring Boot app...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
